### ISSUE TITLE
zrobie fikolka

### ISSUE THREAD

**Issue by F4bianpl** [bopke/RH-RealWeather-Bukkit#4]
zrobie fikolka jak dacie lajkuf duzo

**Comment by F4bianpl** [comment]
laikuicie subskrybujcie i dzwoneczkuuuicie

**Comment by F4bianpl** [comment]
![buzia](https://user-images.githubusercontent.com/44644176/58625456-ccaacf00-82d2-11e9-9157-08a37c7fadb7.jpg)

**Comment by bopke** [comment]
???
